nifty_50 = ['ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'LTIM', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UPL', 'WIPRO']

nifty_bank = ['AUBANK', 'AXISBANK', 'BANDHANBNK', 'BANKBARODA', 'FEDERALBNK', 'HDFCBANK', 'ICICIBANK', 'IDFCFIRSTB', 'INDUSINDBK', 'KOTAKBANK', 'PNB', 'SBIN']

nifty_it = ['COFORGE', 'HCLTECH', 'INFY', 'LTTS', 'LTIM', 'MPHASIS', 'PERSISTENT', 'TCS', 'TECHM', 'WIPRO']

nifty_fin_service = ['AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'CHOLAFIN', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'IEX', 'KOTAKBANK', 'LICHSGFIN', 'MUTHOOTFIN', 'PFC', 'RECLTD', 'SBICARD', 'SBILIFE', 'SHRIRAMFIN', 'SBIN']

nifty_fmcg = ['BRITANNIA', 'COLPAL', 'DABUR', 'EMAMILTD', 'GODREJCP', 'HINDUNILVR', 'ITC', 'MARICO', 'NESTLEIND', 'PGHH', 'RADICO', 'TATACONSUM', 'UBL', 'MCDOWELL-N', 'VBL']

nifty_auto = ['ASHOKLEY', 'BAJAJ-AUTO', 'BALKRISIND', 'BHARATFORG', 'BOSCHLTD', 'EICHERMOT', 'HEROMOTOCO', 'MRF', 'M&M', 'MARUTI', 'MOTHERSON', 'SONACOMS', 'TVSMOTOR', 'TATAMOTORS', 'TIINDIA']

nifty_energy = ['ADANIGREEN', 'ADANITRANS', 'BPCL', 'COALINDIA', 'IOC', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'TATAPOWER']

nifty_metal = ['APLAPOLLO', 'ADANIENT', 'HINDALCO', 'HINDCOPPER', 'HINDZINC', 'JSWSTEEL', 'JSL', 'JINDALSTEL', 'NMDC', 'NATIONALUM', 'RATNAMANI', 'SAIL', 'TATASTEEL', 'VEDL', 'WELCORP']

nifty_pharma = ['ABBOTINDIA', 'ALKEM', 'AUROPHARMA', 'BIOCON', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'GLAND', 'GLAXO', 'GLENMARK', 'GRANULES', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'NATCOPHARM', 'PFIZER', 'SANOFI', 'SUNPHARMA', 'TORNTPHARM', 'ZYDUSLIFE']

nifty_healthcare = ['ABBOTINDIA', 'ALKEM', 'APOLLOHOSP', 'AUROPHARMA', 'BIOCON', 'CIPLA', 'DIVISLAB', 'LALPATHLAB', 'DRREDDY', 'GLENMARK', 'GRANULES', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'MAXHEALTH', 'METROPOLIS', 'SUNPHARMA', 'SYNGENE', 'TORNTPHARM', 'ZYDUSLIFE']

nifty_realty = ['BRIGADE', 'DLF', 'GODREJPROP', 'IBREALEST', 'LODHA', 'MAHLIFE', 'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'SOBHA']

nifty_next_50 = ['ABB', 'ACC', 'ADANIGREEN', 'ATGL', 'ADANITRANS', 'AWL', 'AMBUJACEM', 'BAJAJHLDNG', 'BANKBARODA', 'BERGEPAINT', 'BEL', 'BOSCHLTD', 'CANBK', 'CHOLAFIN', 'COLPAL', 'DABUR', 'DLF', 'DMART', 'GAIL', 'GODREJCP', 'HAVELLS', 'HDFCAMC', 'HAL', 'ICICIGI', 'ICICIPRULI', 'IOC', 'INDIGO', 'INDUSTOWER', 'NAUKRI', 'IRCTC', 'JINDALSTEL', 'LICI', 'MARICO', 'MUTHOOTFIN', 'NYKAA', 'PAGEIND', 'PIIND', 'PIDILITIND', 'PGHH', 'MOTHERSON', 'SBICARD', 'SHREECEM', 'SIEMENS', 'SRF', 'TATAPOWER', 'TORNTPHARM', 'MCDOWELL-N', 'VBL', 'VEDL', 'ZOMATO']

nifty_midcap_50 = ['AUBANK', 'ABBOTINDIA', 'ABCAPITAL', 'ALKEM', 'ASHOKLEY', 'ASTRAL', 'AUROPHARMA', 'BALKRISIND', 'BANDHANBNK', 'BATAINDIA', 'BHARATFORG', 'BIOCON', 'COFORGE', 'CONCOR', 'CUMMINSIND', 'ESCORTS', 'FEDERALBNK', 'GODREJPROP', 'GUJGASLTD', 'HINDPETRO', 'HONAUT', 'IDFCFIRSTB', 'INDHOTEL', 'JUBLFOOD', 'LTTS', 'LICHSGFIN', 'LUPIN', 'MRF', 'M&MFIN', 'MFSL', 'MPHASIS', 'NMDC', 'OBEROIRLTY', 'OFSS', 'PERSISTENT', 'PETRONET', 'POLYCAB', 'PFC', 'PNB', 'RECLTD', 'SHRIRAMFIN', 'SAIL', 'TVSMOTOR', 'TATACOMM', 'TRENT', 'UBL', 'IDEA', 'VOLTAS', 'ZEEL', 'ZYDUSLIFE']

nifty_smallcap_50 = ['AMARAJABAT', 'ANGELONE', 'ANURAS', 'BSE', 'BALAMINES', 'MAHABANK', 'BDL', 'BIKAJI', 'BIRLACORPN', 'BSOFT', 'CESC', 'CAMPUS', 'CDSL', 'CHAMBLFERT', 'CUB', 'CAMS', 'CYIENT', 'EASEMYTRIP', 'MEDANTA', 'GRAPHITE', 'GNFC', 'HFCL', 'HINDCOPPER', 'IDBI', 'IDFC', 'IRB', 'IEX', 'IOB', 'JBCHEPHARM', 'JUBLINGREA', 'KPITTECH', 'LATENTVIEW', 'LXCHEM', 'MANAPPURAM', 'MRPL', 'MAZDOCK', 'MEDPLUS', 'METROPOLIS', 'NATIONALUM', 'PVRINOX', 'RBLBANK', 'RADICO', 'RVNL', 'REDINGTON', 'ROUTE', 'RENUKA', 'SUZLON', 'UCOBANK', 'UTIAMC', 'WELSPUNIND']

allIndices = set(nifty_50 +
                 nifty_bank +
                 nifty_it +
                 nifty_fin_service +
                 nifty_fmcg +
                 nifty_auto +
                 nifty_energy +
                 nifty_metal +
                 nifty_pharma +
                 nifty_healthcare +
                 nifty_realty +
                 nifty_next_50 +
                 nifty_midcap_50 +
                 nifty_smallcap_50)
