nifty50_stocks = ['ADANIPORTS',
 'ASIANPAINT',
 'AXISBANK',
 'BAJAJ-AUTO',
 'BAJFINANCE',
 'BAJAJFINSV',
 'BHARTIARTL',
 'BRITANNIA',
 'CIPLA',
 'COALINDIA',
 'DIVISLAB',
 'DRREDDY',
 'EICHERMOT',
 'GRASIM',
 'HCLTECH',
 'HDFC',
 'HDFCBANK',
 'HDFCLIFE',
 'HEROMOTOCO',
 'HINDALCO',
 'HINDUNILVR',
 'ICICIBANK',
 'INDUSINDBK',
 'INFY',
 'IOC',
 'ITC',
 'JSWSTEEL',
 'KOTAKBANK',
 'LT',
 'M&M',
 'MARUTI',
 'NESTLEIND',
 'NTPC',
 'ONGC',
 'POWERGRID',
 'RELIANCE',
 'SBILIFE',
 'SBIN',
 'SHREECEM',
 'SUNPHARMA',
 'TATAMOTORS',
 'TATASTEEL',
 'TCS',
 'TECHM',
 'TITAN',
 'ULTRACEMCO',
 'UPL',
 'WIPRO',
 'ZEEL']
nifty_bank = ['AUBANK', 'AXISBANK', 'BANDHANBNK', 'BANKBARODA', 'FEDERALBNK', 'HDFCBANK', 'ICICIBANK', 'IDFCFIRSTB', 'INDUSINDBK', 'KOTAKBANK', 'PNB', 'SBIN']

nifty_it = ['COFORGE', 'HCLTECH', 'INFY', 'LTIM', 'LTTS', 'MINDTREE', 'MPHASIS', 'TCS', 'TECHM', 'WIPRO']

nifty_fin_service = ['AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'CHOLAFIN', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HDFC', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'KOTAKBANK', 'MUTHOOTFIN', 'PEL', 'PFC', 'RECLTD', 'SBILIFE', 'SHRIRAMFIN', 'SBIN']

nifty_fmcg = ['BRITANNIA', 'COLPAL', 'DABUR', 'EMAMILTD', 'GODREJCP', 'HINDUNILVR', 'ITC', 'JUBLFOOD', 'MARICO', 'NESTLEIND', 'PGHL', 'TATACONSUM', 'UBL', 'MCDOWELL-N', 'VBL']

nifty_auto = ['AMARAJABAT', 'ASHOKLEY', 'BAJAJ-AUTO', 'BALKRISIND', 'BHARATFORG', 'BOSCHLTD', 'EICHERMOT', 'ESCORTS', 'EXIDEIND', 'HEROMOTOCO', 'M&M', 'MARUTI', 'MRF', 'TATAMOTORS', 'TVSMOTOR']

nifty_energy = ['ADANIGREEN', 'ADANITRANS', 'BPCL', 'GAIL', 'HINDPETRO', 'IOC', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'TATAPOWER']

nifty_metal = ['ADANIENT', 'APLAPOLLO', 'COALINDIA', 'HINDALCO', 'HINDZINC', 'JINDALSTEL', 'JSWSTEEL', 'MOIL', 'NATIONALUM', 'NMDC', 'RATNAMANI', 'SAIL', 'TATASTEEL', 'VEDL', 'WELCORP']

nifty_pharma = ['ABBOTINDIA', 'ALEMBICLTD', 'ALKEM', 'AUROPHARMA', 'BIOCON', 'ZYDUSLIFE', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'GLAND', 'GLENMARK', 'GRANULES', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'NATCOPHARM', 'PFIZER', 'STAR', 'SUNPHARMA', 'TORNTPHARM', 'ZYDUSWELL']

nifty_healthcare = ['ABBOTINDIA', 'ALKEM', 'APOLLOHOSP', 'AUROPHARMA', 'BIOCON', 'ZYDUSLIFE', 'CIPLA', 'DIVISLAB', 'LALPATHLAB', 'DRREDDY', 'FORTIS', 'GLENMARK', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'NATCOPHARM', 'PFIZER', 'SANOFI', 'SUNPHARMA', 'TORNTPHARM']

nifty_realty = ['BRIGADE', 'DLF', 'GODREJPROP', 'HEMIPROP', 'IBREALEST', 'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'SOBHA', 'SUNTECK']

nifty_next_50 = ['ACC', 'ADANIENT', 'ADANITRANS', 'AMBUJACEM', 'BAJAJHLDNG', 'BANDHANBNK', 'BANKBARODA', 'BERGEPAINT', 'INDUSTOWER', 'BIOCON', 'BOSCHLTD', 'ZYDUSLIFE', 'CHOLAFIN', 'COLPAL', 'DABUR', 'DLF', 'DMART', 'GAIL', 'GODREJCP', 'HAVELLS', 'HDFCAMC', 'ICICIGI', 'ICICIPRULI', 'IOC', 'INDIGO', 'JUBLFOOD', 'LTIM', 'LUPIN', 'MARICO', 'MINDTREE', 'MUTHOOTFIN', 'NAUKRI', 'NMDC', 'NYKAA', 'PIDILITIND', 'PIIND', 'PEL', 'PGHL', 'PNB', 'SIEMENS', 'SRF', 'SAIL', 'TORNTPHARM', 'MCDOWELL-N', 'VEDL']
