nifty_50 = ['ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'LTIM', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UPL', 'WIPRO']

nifty_bank = ['AUBANK', 'AXISBANK', 'BANDHANBNK', 'BANKBARODA', 'FEDERALBNK', 'HDFCBANK', 'ICICIBANK', 'IDFCFIRSTB', 'INDUSINDBK', 'KOTAKBANK', 'PNB', 'SBIN']

nifty_it = ['COFORGE', 'HCLTECH', 'INFY', 'LTTS', 'LTIM', 'MPHASIS', 'PERSISTENT', 'TCS', 'TECHM', 'WIPRO']

nifty_fin_service = ['AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'CHOLAFIN', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'IEX', 'KOTAKBANK', 'LICHSGFIN', 'MUTHOOTFIN', 'PFC', 'RECLTD', 'SBICARD', 'SBILIFE', 'SHRIRAMFIN', 'SBIN']

nifty_fmcg = ['BRITANNIA', 'COLPAL', 'DABUR', 'EMAMILTD', 'GODREJCP', 'HINDUNILVR', 'ITC', 'MARICO', 'NESTLEIND', 'PGHH', 'RADICO', 'TATACONSUM', 'UBL', 'MCDOWELL-N', 'VBL']

nifty_auto = ['ASHOKLEY', 'BAJAJ-AUTO', 'BALKRISIND', 'BHARATFORG', 'BOSCHLTD', 'EICHERMOT', 'HEROMOTOCO', 'MRF', 'M&M', 'MARUTI', 'MOTHERSON', 'SONACOMS', 'TVSMOTOR', 'TATAMOTORS', 'TIINDIA']

nifty_energy = ['ADANIGREEN', 'ADANITRANS', 'BPCL', 'COALINDIA', 'IOC', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'TATAPOWER']

nifty_metal = ['APLAPOLLO', 'ADANIENT', 'HINDALCO', 'HINDCOPPER', 'HINDZINC', 'JSWSTEEL', 'JSL', 'JINDALSTEL', 'NMDC', 'NATIONALUM', 'RATNAMANI', 'SAIL', 'TATASTEEL', 'VEDL', 'WELCORP']

nifty_pharma = ['ABBOTINDIA', 'ALKEM', 'AUROPHARMA', 'BIOCON', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'GLAND', 'GLAXO', 'GLENMARK', 'GRANULES', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'NATCOPHARM', 'PFIZER', 'SANOFI', 'SUNPHARMA', 'TORNTPHARM', 'ZYDUSLIFE']

nifty_healthcare = ['ABBOTINDIA', 'ALKEM', 'APOLLOHOSP', 'AUROPHARMA', 'BIOCON', 'CIPLA', 'DIVISLAB', 'LALPATHLAB', 'DRREDDY', 'GLENMARK', 'GRANULES', 'IPCALAB', 'LAURUSLABS', 'LUPIN', 'MAXHEALTH', 'METROPOLIS', 'SUNPHARMA', 'SYNGENE', 'TORNTPHARM', 'ZYDUSLIFE']

nifty_realty = ['BRIGADE', 'DLF', 'GODREJPROP', 'IBREALEST', 'LODHA', 'MAHLIFE', 'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'SOBHA']

nifty_next_50 = ['ABB', 'ACC', 'ADANIGREEN', 'ATGL', 'ADANITRANS', 'AWL', 'AMBUJACEM', 'BAJAJHLDNG', 'BANKBARODA', 'BERGEPAINT', 'BEL', 'BOSCHLTD', 'CANBK', 'CHOLAFIN', 'COLPAL', 'DABUR', 'DLF', 'DMART', 'GAIL', 'GODREJCP', 'HAVELLS', 'HDFCAMC', 'HAL', 'ICICIGI', 'ICICIPRULI', 'IOC', 'INDIGO', 'INDUSTOWER', 'NAUKRI', 'IRCTC', 'JINDALSTEL', 'LICI', 'MARICO', 'MUTHOOTFIN', 'NYKAA', 'PAGEIND', 'PIIND', 'PIDILITIND', 'PGHH', 'MOTHERSON', 'SBICARD', 'SHREECEM', 'SIEMENS', 'SRF', 'TATAPOWER', 'TORNTPHARM', 'MCDOWELL-N', 'VBL', 'VEDL', 'ZOMATO']

nifty_midcap_50 = ['AUBANK', 'ABBOTINDIA', 'ABCAPITAL', 'ALKEM', 'ASHOKLEY', 'ASTRAL', 'AUROPHARMA', 'BALKRISIND', 'BANDHANBNK', 'BATAINDIA', 'BHARATFORG', 'BIOCON', 'COFORGE', 'CONCOR', 'CUMMINSIND', 'ESCORTS', 'FEDERALBNK', 'GODREJPROP', 'GUJGASLTD', 'HINDPETRO', 'HONAUT', 'IDFCFIRSTB', 'INDHOTEL', 'JUBLFOOD', 'LTTS', 'LICHSGFIN', 'LUPIN', 'MRF', 'M&MFIN', 'MFSL', 'MPHASIS', 'NMDC', 'OBEROIRLTY', 'OFSS', 'PERSISTENT', 'PETRONET', 'POLYCAB', 'PFC', 'PNB', 'RECLTD', 'SHRIRAMFIN', 'SAIL', 'TVSMOTOR', 'TATACOMM', 'TRENT', 'UBL', 'IDEA', 'VOLTAS', 'ZEEL', 'ZYDUSLIFE']

nifty_smallcap_50 = ['AMARAJABAT', 'ANGELONE', 'ANURAS', 'BSE', 'BALAMINES', 'MAHABANK', 'BDL', 'BIKAJI', 'BIRLACORPN', 'BSOFT', 'CESC', 'CAMPUS', 'CDSL', 'CHAMBLFERT', 'CUB', 'CAMS', 'CYIENT', 'EASEMYTRIP', 'MEDANTA', 'GRAPHITE', 'GNFC', 'HFCL', 'HINDCOPPER', 'IDBI', 'IDFC', 'IRB', 'IEX', 'IOB', 'JBCHEPHARM', 'JUBLINGREA', 'KPITTECH', 'LATENTVIEW', 'LXCHEM', 'MANAPPURAM', 'MRPL', 'MAZDOCK', 'MEDPLUS', 'METROPOLIS', 'NATIONALUM', 'PVRINOX', 'RBLBANK', 'RADICO', 'RVNL', 'REDINGTON', 'ROUTE', 'RENUKA', 'SUZLON', 'UCOBANK', 'UTIAMC', 'WELSPUNIND']

nifty_500 = [
    '360ONE', '3MINDIA', 'ABB', 'ACC', 'AIAENG', 'APLAPOLLO', 'AUBANK', 'AARTIDRUGS', 'AARTIIND', 'AAVAS',
    'ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ATGL', 'ADANITRANS', 'AWL', 'ABCAPITAL',
    'ABFRL', 'AEGISCHEM', 'AETHER', 'AFFLE', 'AJANTPHARM', 'APLLTD', 'ALKEM', 'ALKYLAMINE', 'AMARAJABAT', 'AMBER',
    'AMBUJACEM', 'ANGELONE', 'ANURAS', 'APARINDS', 'APOLLOHOSP', 'APOLLOTYRE', 'APTUS', 'ACI', 'ASAHIINDIA', 'ASHOKLEY',
    'ASIANPAINT', 'ASTERDM', 'ASTRAL', 'ATUL', 'AUROPHARMA', 'AVANTIFEED', 'DMART', 'AXISBANK', 'BASF', 'BEML', 'BLS',
    'BSE', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK',
    'BANKBARODA', 'BANKINDIA', 'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BERGEPAINT', 'BDL', 'BEL', 'BHARATFORG', 'BHEL',
    'BPCL', 'BHARTIARTL', 'BIKAJI', 'BIOCON', 'BIRLACORPN', 'BSOFT', 'BLUEDART', 'BLUESTARCO', 'BBTC', 'BORORENEW',
    'BOSCHLTD', 'BRIGADE', 'BCG', 'BRITANNIA', 'MAPMYINDIA', 'CCL', 'CESC', 'CGPOWER', 'CIEINDIA', 'CRISIL', 'CSBBANK',
    'CAMPUS', 'CANFINHOME', 'CANBK', 'CGCL', 'CARBORUNIV', 'CASTROLIND', 'CEATLTD', 'CENTRALBK', 'CDSL', 'CENTURYPLY',
    'CENTURYTEX', 'CERA', 'CHALET', 'CHAMBLFERT', 'CHEMPLASTS', 'CHOLAHLDNG', 'CHOLAFIN', 'CIPLA', 'CUB', 'CLEAN',
    'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CAMS', 'CONCOR', 'COROMANDEL', 'CRAFTSMAN', 'CREDITACC', 'CROMPTON',
    'CUMMINSIND', 'CYIENT', 'DCMSHRIRAM', 'DLF', 'DABUR', 'DALBHARAT', 'DATAPATTNS', 'DEEPAKFERT', 'DEEPAKNTR', 'DELHIVERY',
    'DELTACORP', 'DEVYANI', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY',  'EIDPARRY', 'EIHOTEL', 'EPL',
    'EASEMYTRIP', 'EICHERMOT', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN', 'EQUITASBNK', 'ERIS', 'ESCORTS',
    'EXIDEIND', 'FDC', 'NYKAA', 'FEDERALBNK', 'FACT', 'FINEORG', 'FINCABLES', 'FINPIPE', 'FSL', 'FIVESTAR', 'FORTIS',
    'GRINFRA', 'GAIL', 'GMMPFAUDLR', 'GMRINFRA', 'GALAXYSURF', 'GARFIBRES', 'GICRE', 'GLAND', 'GLAXO', 'GLENMARK',
    'MEDANTA', 'GOCOLORS', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES', 'GRAPHITE',
    'GRASIM', 'GESHIP', 'GREENPANEL', 'GRINDWELL', 'GUJALKALI', 'GAEL', 'FLUOROCHEM', 'GUJGASLTD', 'GNFC', 'GPPL',
    'GSFC', 'GSPL', 'HEG', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HFCL', 'HLEGLAS', 'HAPPSTMNDS', 'HAVELLS',
    'HEROMOTOCO', 'HIKAL', 'HINDALCO', 'HGS', 'HAL', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'POWERINDIA',
    'HOMEFIRST', 'HONAUT', 'HUDCO', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ISEC', 'IDBI', 'IDFCFIRSTB', 'IDFC', 'IFBIND',
    'IIFL', 'IRB', 'ITC', 'ITI', 'INDIACEM', 'IBULHSGFIN', 'IBREALEST', 'INDIAMART', 'INDIANB', 'IEX', 'INDHOTEL', 'IOC',
    'IOB', 'IRCTC', 'IRFC', 'INDIGOPNTS', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'INFIBEAM', 'NAUKRI', 'INFY', 'INGERRAND',
    'INTELLECT', 'INDIGO', 'IPCALAB', 'JBCHEPHARM', 'JKCEMENT', 'JBMA', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSWENERGY',
    'JSWSTEEL', 'JAMNAAUTO', 'JSL', 'JINDALSTEL', 'JINDWORLD', 'JUBLFOOD', 'JUBLINGREA', 'JUBLPHARMA', 'JUSTDIAL', 'JYOTHYLAB',
    'KPRMILL', 'KEI', 'KNRCON', 'KPITTECH', 'KRBL', 'KSB', 'KAJARIACER', 'KPIL', 'KALYANKJIL', 'KANSAINER', 'KARURVYSYA',
    'KEC', 'KENNAMET', 'RUSTOMJEE', 'KFINTECH', 'KOTAKBANK', 'KIMS', 'L&TFH', 'LTTS', 'LICHSGFIN', 'LTIM', 'LAXMIMACH', 'LT',
    'LATENTVIEW', 'LAURUSLABS', 'LXCHEM', 'LEMONTREE', 'LICI', 'LINDEINDIA', 'LUPIN', 'LUXIND', 'MMTC', 'MRF', 'MTARTECH',
    'LODHA', 'MGL', 'M&MFIN', 'M&M', 'MHRIL', 'MAHLIFE', 'MAHLOG', 'MANAPPURAM', 'MRPL', 'MANKIND', 'MARICO', 'MARUTI',
    'MASTEK', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'MEDPLUS', 'MFL', 'METROBRAND', 'METROPOLIS', 'MSUMI', 'MOTILALOFS', 'MPHASIS',
    'MCX', 'MUTHOOTFIN', 'NATCOPHARM', 'NBCC', 'NCC', 'NHPC', 'NLCINDIA', 'NMDC', 'NSLNISP', 'NOCIL', 'NTPC', 'NH', 'NATIONALUM',
    'NAVINFLUOR', 'NAZARA', 'NESTLEIND', 'NETWORK18', 'NAM-INDIA', 'NUVOCO', 'OBEROIRLTY', 'ONGC', 'OIL', 'OLECTRA', 'PAYTM',
    'OFSS', 'ORIENTELEC', 'POLICYBZR', 'PCBL', 'PIIND', 'PNBHOUSING', 'PNCINFRA', 'PVRINOX', 'PAGEIND', 'PATANJALI', 'PERSISTENT',
    'PETRONET', 'PFIZER', 'PHOENIXLTD', 'PIDILITIND', 'PEL', 'PPLPHARMA', 'POLYMED', 'POLYCAB', 'POLYPLEX', 'POONAWALLA', 'PFC',
    'POWERGRID', 'PRAJIND', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PGHH', 'PNB', 'QUESS', 'RBLBANK', 'RECLTD', 'RHIM', 'RITES',
    'RADICO', 'RVNL', 'RAIN', 'RAINBOW', 'RAJESHEXPO', 'RALLIS', 'RCF', 'RATNAMANI', 'RTNINDIA', 'RAYMOND', 'REDINGTON', 'RELAXO',
    'RELIANCE', 'RBA', 'ROSSARI', 'ROUTE', 'SBICARD', 'SBILIFE', 'SJVN', 'SKFINDIA', 'SRF', 'MOTHERSON', 'SANOFI', 'SAPPHIRE',
    'SCHAEFFLER', 'SHARDACROP', 'SHOPERSTOP', 'SHREECEM', 'RENUKA', 'SHRIRAMFIN', 'SHYAMMETL', 'SIEMENS', 'SOBHA', 'SOLARINDS',
    'SONACOMS', 'SONATSOFTW', 'STARHEALTH', 'SBIN', 'SAIL', 'SWSOLAR', 'STLTECH', 'SUMICHEM', 'SPARC', 'SUNPHARMA', 'SUNTV',
    'SUNDARMFIN', 'SUNDRMFAST', 'SUNTECK', 'SUPRAJIT', 'SUPREMEIND', 'SUVENPHAR', 'SUZLON', 'SWANENERGY', 'SYNGENE', 'TCIEXP',
    'TCNSBRANDS', 'TTKPRESTIG', 'TV18BRDCST', 'TVSMOTOR', 'TMB', 'TANLA', 'TATACHEM', 'TATACOMM', 'TCS', 'TATACONSUM', 'TATAELXSI',
    'TATAINVEST', 'TATAMTRDVR', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TTML', 'TEAMLEASE', 'TECHM', 'TEJASNET', 'NIACL', 'RAMCOCEM',
    'THERMAX', 'TIMKEN', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TCI', 'TRENT', 'TRIDENT', 'TRIVENI', 'TRITURBINE', 'TIINDIA', 'UCOBANK',
    'UFLEX', 'UNOMINDA', 'UPL', 'UTIAMC', 'ULTRACEMCO', 'UNIONBANK', 'UBL', 'MCDOWELL-N', 'VGUARD', 'VMART', 'VIPIND', 'VAIBHAVGBL',
    'VTL', 'VARROC', 'VBL', 'MANYAVAR', 'VEDL', 'VIJAYA', 'VINATIORGA', 'IDEA', 'VOLTAS', 'WELCORP', 'WELSPUNIND', 'WESTLIFE',
    'WHIRLPOOL', 'WIPRO', 'YESBANK', 'ZFCVINDIA', 'ZEEL', 'ZENSARTECH', 'ZOMATO', 'ZYDUSLIFE', 'ZYDUSWELL', 'ECLERX'
]

allIndices = set(nifty_50 +
                 nifty_bank +
                 nifty_it +
                 nifty_fin_service +
                 nifty_fmcg +
                 nifty_auto +
                 nifty_energy +
                 nifty_metal +
                 nifty_pharma +
                 nifty_healthcare +
                 nifty_realty +
                 nifty_next_50 +
                 nifty_midcap_50 +
                 nifty_smallcap_50+
                 nifty_500)

# Updated list of holidays
holidays = [
    # 2019
    'January 26, 2019', 'March 04, 2019', 'March 21, 2019', 'April 17, 2019', 'April 19, 2019', 
    'May 01, 2019', 'June 05, 2019', 'August 12, 2019', 'August 15, 2019', 'September 02, 2019', 
    'October 02, 2019', 'October 08, 2019', 'October 28, 2019', 'November 12, 2019', 'December 25, 2019',
    # 2020
    'January 26, 2020', 'February 21, 2020', 'March 10, 2020', 'April 02, 2020', 'April 06, 2020', 
    'April 10, 2020', 'May 01, 2020', 'May 25, 2020', 'August 03, 2020', 'August 15, 2020', 
    'August 31, 2020', 'October 02, 2020', 'November 16, 2020', 'November 30, 2020', 'December 25, 2020',
    # 2021
    'January 26, 2021', 'March 11, 2021', 'March 29, 2021', 'April 02, 2021', 'April 14, 2021', 
    'April 21, 2021', 'May 13, 2021', 'July 21, 2021', 'August 19, 2021', 'September 10, 2021', 
    'October 15, 2021', 'November 04, 2021', 'November 19, 2021',
    # 2022
    'January 26, 2022', 'March 01, 2022', 'March 18, 2022', 'April 14, 2022', 'April 15, 2022', 
    'May 03, 2022', 'August 09, 2022', 'August 15, 2022', 'August 31, 2022', 'October 05, 2022', 
    'October 24, 2022', 'October 26, 2022', 'November 08, 2022',
    # 2023
    'January 26, 2023', 'March 07, 2023', 'March 30, 2023', 'April 04, 2023', 'April 07, 2023', 
    'April 14, 2023', 'May 01, 2023', 'June 29, 2023', 'August 15, 2023', 'September 19, 2023', 
    'October 02, 2023', 'October 24, 2023', 'November 14, 2023', 'November 27, 2023', 'December 25, 2023'
]